#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
TERM=xterm-256color

# Source aliases. This allows the same aliases to be shared between bash and zsh
source "${ZDOTDIR:-$HOME}/.aliashrc"
# Source functions. This allows the same functions to be shared between bash and zsh
source "${ZDOTDIR:-$HOME}/.functionshrc"

source "${ZDOTDIR:-$HOME}/.afterzshrc"


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
