#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
TERM=xterm-256color
# this enables using other defined aliases with sudo
alias sudo='sudo '
alias v='nvim'
alias g='git'
#alias for gitting latest versions in version sorted order
alias gtag='git tag -n1 | sort -V | tail'
alias gbranch='git branch'
alias gadd='git add -A'
alias gdiff='git difftool'
alias gcommit='git commit'
alias gpush='git push'
alias gpull='git pull'
alias glog='git log --decorate --stat --graph'
alias gdev='git checkout develop'
alias s='git status'

alias c='cd'
alias c.='cd ..'
alias cacs='cd /home/jesse/hacking/acs'
alias cvim="${ZDOTDIR:-$HOME}/.config/nvim"

source "${ZDOTDIR:-$HOME}/.afterzshrc"
